### PR TITLE
Fixes for your suggestions

### PR DESCRIPTION
**Pull request by adamcoulombe**
- Change to small pointing arrow.
- Remove "all" from copy options.
- Calculate width of copy options so it shouldn't get cut off.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thank you, merged!

Tip: you may want to look into [ES6 template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), they make this kind of string concatenation look much nicer.

**Comment by adamcoulombe** [comment]
True, I think you would need a compiler though to make it reliable on the
client side though, no?

**Comment by LeaVerou** [comment]
They're practically supported everywhere at this point!
image

I doubt anyone who uses cubic-bezier.com is using IE11.

**Comment by adamcoulombe** [comment]
Fair enough! thanks for the heads up.

**Pull request merged**
